### PR TITLE
Don't block startup of Home Assistant

### PR DESCRIPTION
**Pull request by balloob**
Untested

Background: https://github.com/home-assistant/core/issues/37931#issuecomment-661995443

### CODE REVIEW

**Comment by elad-bar** [comment]
the solution you've propused kind of stack the component as once the component is loaded and initialized, it should open a websocket connection and start listen.

I need something to take place after few seconds, so I understand that `async_call_later` will not work,
what will happen if i'll set `async_track_time_interval`, will I get the same issue?

asking because for me it works always, even without the change.

thanks

**Comment by balloob** [comment]
Isn't the web socket connection achieved via the data manager? By using `hass.loop.create_task`, it will run outside of HA tracking system. 

Any event helper of HA will cause your job to be tracked.

**Comment by balloob** [comment]
Waiting 2 seconds wont' work, because as long as your setup takes longer than that, it ends up Home Assistant waitng for it and it won't finish.

**Comment by balloob** [comment]
My fix will load everything as normal, except the data manager will be initialized outside of what HA tracks.

**Comment by elad-bar** [comment]
ok, fixed it, needed to switch the order of actions

**Comment by elad-bar** [comment]
@ballob, thanks a lot for the assistance!

**Pull request closed without merging**
